# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'TVShows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShows
  pod 'SVProgressHUD'
  pod 'Alamofire'
  pod 'CodableAlamofire'
  pod "PromiseKit/CorePromise", "~> 6.0"
  pod 'PromiseKit/Alamofire'
  pod 'Kingfisher', '~> 4.0'
  pod 'KeychainAccess'
end
